export {default as LoginPage} from './Login'
export {default as RegisterPage} from './Register'
export {default as EditProfilePage} from './EditProfile'
export {default as HomePage} from './Home'
export {default as LogoutPage} from './Logout'
export {default as QuizzesPage} from "./Quizzes"
export {default as QuizPage} from "./Quiz"
export {default as CoursesPage} from "./Courses"
export {default as CourseDetailPage} from "./CourseDetail"
export {default as LessonDetailPage} from "./LessonDetail"
export {default as HandleVerifyEmail} from "./HandleVerifyEmail"
export {default as ForgotPasswordPage} from "./ForgotPassword"
export {default as CourseCreatePage} from "./CourseCreate"
export {default as EditCoursePage} from "./EditCourse"
export {default as PostsPage} from "./Posts"
export {default as QuizCreatePage} from "./QuizCreate"
export {default as FriendsPage} from "./Friends"
export {default as LessonCreate} from "./LessonCreate"
export {default as AdminPage} from "./Admin"